# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lemonldap-NG-Portal
version:      0.64
version_from: lib/Lemonldap/NG/Portal.pm
installdirs:  site
requires:
    Apache::Session:               0
    CGI:                           3.08
    Lemonldap::NG::Manager:        0.4
    Net::LDAP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
