--- #YAML:1.0
name:               Lemonldap-NG-Portal
version:            1.0.5
abstract:           The authentication portal part of Lemonldap::NG Web-SSO
author:
    - Xavier Guimard <x.guimard@free.fr>, Clément Oudot <clement@oodo.net>, Thomas Chemineau <thomas.chemineau@gmail.com>, Mikael Ates <mikael.ates@univ-st-etienne.fr>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Crypt::OpenSSL::X509:  0
    IO::String:           0
    SOAP::Lite:           0
requires:
    Apache::Session:      0
    CGI:                  3.08
    Clone:                0
    Crypt::OpenSSL::X509:  0
    File::Basename:       0
    HTML::Template:       0
    IO::String:           0
    Lemonldap::NG::Common:  1.0.5
    Lemonldap::NG::Handler:  1.0.5
    MIME::Lite:           0
    Net::LDAP:            0
    SOAP::Lite:           0
    String::Random:       0
    XML::LibXML:          0
    XML::LibXSLT:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Convert::PEM:         0
    Crypt::OpenSSL::X509:  0
    Email::Date::Format:  0
    Lasso:                2.3.0
    Net::OpenID::Consumer:  0
    Net::OpenID::Server:  0
    Net::Twitter:         0
