--- #YAML:1.0
name:                Lemonldap-NG-Portal
version:             0.86
abstract:            The authentication portal part of Lemonldap::NG Web-SSO
license:             ~
author:              
    - Xavier Guimard <x.guimard@free.fr>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Apache::Session:               0
    CGI:                           3.08
    CGI::Session:                  0
    HTML::Template:                0
    Lemonldap::NG::Common:         0.9
    Lemonldap::NG::Handler:        0.9
    Net::LDAP:                     0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
