# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lemonldap-NG-Portal
version:      0.1
version_from: lib/Lemonldap/NG/Portal.pm
installdirs:  vendor
requires:
    Apache::Session:               0
    CGI:                           0
    MIME::Base64:                  0
    Net::LDAP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
